name: Go Format Check
on: [push, pull_request]

jobs:
  checks and tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.24'
    - name: Check Go version
      run: go version
    - name: Check Go formatting
      run: |
        if [ "$(gofmt -d . | wc -l)" -gt 0 ]; then
          echo "Go code is not formatted properly:"
          gofmt -d .
          exit 1
        fi
        echo "Go code is properly formatted"
    - name: Download Go dependencies
      run: go mod download
    - name: Test Go code
      run: |
        go test -v ./...
        if [ $? -ne 0 ]; then
          echo "Go tests failed"
          exit 1
        fi
        echo "Go tests passed"
    - name: Check build
      run: |
        go build main.go
        if [ $? -ne 0 ]; then
          echo "Go build failed"
          exit 1
        fi